version: '3.7'
services:
  api_gateway:
    build:
      context: ./apiGateway
      target: development
      args:
        BUILD_VERSION: development
        PORT: 3000
    environment: 
      PORT: 3000
      UI_ENDPOINT: http://ui:3001
      SPOTIFY_SERVICE_ENDPOINT: http://spotify_service:3002
    volumes: 
      - ./apiGateway/src:/usr/src/app/src
      - ./apiGateway/index.js:/usr/src/app/index.js
    ports:
      - "3000:3000"

  ui:
    build:
      context: ./ui
      target: development
      args:
        BUILD_VERSION: development
        PORT: 3001
    environment: 
      PORT: 3001
      AUTH_DOMAIN: ${AUTH_DOMAIN}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
    volumes: 
      - ./ui/src:/usr/src/app/src

  spotify_service:
    build:
      context: ./spotifyService
      target: development
      args:
        BUILD_VERSION: development
        PORT: 3002
    environment: 
      PORT: 3002
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      BASE_URL: http://localhost:3000/api/spotify
    volumes: 
      - ./spotifyService/src:/usr/src/app/src     
