version: '3.7'
services:
  api_gateway:
    build:
      context: ./apiGateway
      target: production
      args:
        BUILD_VERSION: production
        PORT: 3000
    environment: 
      PORT: 3000
      UI_ENDPOINT: http://ui:3001
      SPOTIFY_SERVICE_ENDPOINT: http://spotify_service:3002
    ports:
      - "80:3000"

  ui:
    build:
      context: ./ui
      target: production
      args:
        BUILD_VERSION: production
        PORT: 3001
    environment: 
      PORT: 3001

  spotify_service:
    build:
      context: ./spotifyService
      target: production
      args:
        BUILD_VERSION: production
        PORT: 3002
    environment: 
      PORT: 3002
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      BASE_URL: http://localhost:3000/api/spotify