version: '3.7'
services:
  api_gateway:
    build:
      context: ./apiGateway
      target: production
      args:
        BUILD_VERSION: production
        PORT: 3000
    environment: 
      PORT: 3000
      UI_ENDPOINT: http://ui:3001
    ports:
      - "80:3000"

  ui:
    build:
      context: ./ui
      target: production
      args:
        BUILD_VERSION: production
        AUTH_DOMAIN: ${AUTH_DOMAIN}
        AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
        PORT: 3001
    environment: 
      PORT: 3001